# Generated by Django 5.2.17 on 2026-09-08 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=150)),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=100)),
                ('redoublant', models.BooleanField(default=False)),
                ('statut', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2)),
                ('composition_francaise', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('orthographe_grammaire', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('expression_orale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hist_geo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('espagnol', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('allemand', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('anglais', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('francais', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('conduite', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('edhc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('svt', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('physiques_chimie', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mathematiques', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('philosophie', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moyenne_trimestrielle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rang', models.PositiveIntegerField(blank=True, null=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='analyse.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='analyse.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='analyse.eleve')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('eleve', 'annee_scolaire', 'trimestre'), name='resultat_unique_par_trimestre')],
            },
        ),
    ]
